### ISSUE TITLE
Configure distance between unconnected nodes

### ISSUE THREAD

**Issue by torman119** [cytoscape/cytoscape.js-euler#11]
When having several groups of unconnected nodes I have not found an option to configure the distance between the groups. In the following case the groups should be closer together:
![image](https://user-images.githubusercontent.com/4785972/27238869-e8b4ade6-52ce-11e7-839e-a218dd3c54f8.png)

**Comment by maxkfranz** [comment]
There's no packing algorithm iirc, but you could add a pull/gravity force to pull the components closer together
