### ISSUE TITLE
Loading as ES module crashes Firefox 54

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js-euler#12]
I use Firefox 54 (64 bit) with ES modules enabled and successfully use them throughout my own code but when I use `import euler from '../lib/cytoscape-euler.js';` (Firefox doesn't seem to accept module names without path and extension), the browser crashes without console statements.

**Comment by maxkfranz** [comment]
ES modules can only work if you build a bundle using browserify or webpack.  It's not possible to publish ES module libs that are backwards compatible with non-ES-module browsers.

**Comment by KonradHoeffner** [comment]
But Firefox 54 supports ES modules, at least when the experimental flag is enabled. Shouldn't it work in that case?

**Comment by maxkfranz** [comment]
No, it's not possible to support ES6 `export`/`import` directly (i.e. no webpack or browserify) and also support CommonJS-only environments, like node<=6.

You can't try-catch for syntax errors like missing `export`.  Try running this on node@6:

```js
try {
  export function foo(){
    console.log('export');
  }
} catch(err){
  module.exports = { foo: function(){
    console.log('module.exports');
  } };
}
```

```
/private/tmp/exp.js:2
  export function foo(){
  ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

So, we basically have to choose between supporting only ES modules or only CJS modules.  Very few environments support ES modules yet.  So we can support either only those few environments, or we can support all of node/webpack/browserify/globals with CJS.
