### ISSUE TITLE
After running euler, cytoscape JSON output cannot be serialized

### ISSUE THREAD

**Issue by jspautsch** [cytoscape/cytoscape.js-euler#15]
The euler layout adds a "body" property to the node's position object, which is included in cytoscape's JSON output. The body property is an object that includes a reference to the cytoscape element (position.body._cyNode), which prevents the JSON output from being serialized due to the cyclic object reference. There's also another "_scratch" property which is a cyclic reference to "position".

**Comment by maxkfranz** [comment]
I tried `JSON.stringify( cy.json() )` on two demos, and they worked.  I didn't notice anything but x and y in the position objects either.

Please provide a reproducible test case.

**Comment by michalhabala** [comment]
I have the same problem. After some testing I found out that the problem (added "body" property to the node's position object) occures only when I use Euler with animate=false. When I set the animate property to true or "end" then the "body" property is not added.

One more thing: this bug relates to CY 3.2.0 and above. When I switched to 3.1.5 the "body" property was not added.
