### ISSUE TITLE
API fatal error handler returned after process out of memory

### ISSUE THREAD

**Issue by kimbuz** [cytoscape/cytoscape.js-euler#18]
Hi, I am trying to run cytoscape-euler using node in order to preprocess all positions for dots (around 1K) with some of them already with fixed position. Runing in Chrome (browser) it works, but trying to get the same result with node.js fails:

> #
> # Fatal error in , line 0
> # API fatal error handler returned after process out of memory
> #

I am using this setup for layout Euler. I tried same code with cose, cose-bilken, cola and works, but no luck with euler. The idea is just to preprocess point location and save result for viewers with a simple preset layout.

```
var layoutSet = {
        name: 'euler',
        animate: false,
        fit: false,
        springLength: 120,
        springCoeff: 0.001,
        mass: 60,
        gravity: -2,
        pull: 0.01,
        theta: 0.666,
        dragCoeff: 0.02,
        movementThreshold: 1,
        timeStep: 20,
        refresh: 10,
        maxIterations: 1000,
        maxSimulationTime: 4000,
      };
      console.log('Building Graph');
      cy.layout( layoutSet ).run();

```
Thanks!

**Comment by mydoghasworms** [comment]
Same here.

**Comment by maxkfranz** [comment]
Could you attach a sample script and data file to reproduce your issue?

It should be a minimal example that is runnable via `npm start`.

- package.json
- index.js
- graph.json

**Comment by Letrab** [comment]
Same here, seems that it loops endlessly on this line: `while (!insertStack.isEmpty()) {`

**Comment by Odinodin** [comment]
Upgraded from 1.0.0 to 1.2.2 and hit the same issue. When I set randomize to true, I no longer got the stack error. Randomize is default set to false as far as I can tell

**Comment by denglouhen** [comment]
Same here, after I add new nodes and run the layout again, the web page is stuck  and devtools run into the code "while (!insertStack.isEmpty()) {“

**Comment by slck9596** [comment]
I have this issue as well when randomized option is false. Since, false option is available, it shouldn't run into infinite loops right?

**Comment by adippel** [comment]
That issue still exists in 2024. Is the only option really to set randomized to true? I want to have a consistent graph while dynamically updating the graph but I cannot achieve this with this behavior being present.
