### ISSUE TITLE
Test layout output with several datasets

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-euler#2]
It would be good to test the library with several different graphs to evaluate quality and speed.

Here are some types of graphs we should test:

- [x] Large graph (maybe galfiltered example from Cytoscape)
- [ ] Medium planar graph
- [ ] Medium compound graph
- [x] Small graph
- [ ] Biology
  - [ ] Protein-protein or gene-gene graph
  - [ ] SBGN / pathway graph
- [ ] Social media graph
- [ ] Data from one of the apps in the ["used by" list](http://js.cytoscape.org/#introduction/factsheet)

The graphs can come from 

- existing Cytoscape.js demos,
- Cytoscape.js JSON files,
- XGMML loaded into [Cytoscape desktop](http://cytoscape.org) and exported as JSON,
- GRAPHML loaded into [Cytoscape desktop](http://cytoscape.org) and exported as JSON, or
- SBGNML exported to JSON with @d2fong's library.

**Comment by schae234** [comment]
I have some medium/large biological networks (hundreds to thousands) (co-expression) in JSON if you want something to benchmark off of.

**Comment by maxkfranz** [comment]
@schae234 That would be great.  Could you put them in a PR in the example-graphs dir?
