### ISSUE TITLE
New feature brainstorming

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-euler#4]
Please comment on this issue with new feature ideas not already discussed in the readme: https://github.com/cytoscape/cytoscape.js-euler#mozilla-global-sprint-2017-instructions

**Comment by KonradHoeffner** [comment]
Please add multi threading, 10 seconds of layouting for 2000 classes and 4500 properties on Firefox 54 (64 bit) even with a Core i7-4790 is probably too much for my users.
With 4700 classes and 900 properties it takes > 30 s on the same machine in both Firefox 54 and Chrome 59.
P.S.: But thank you very much for developing this layout, it is still the only one I found that can layout graphs of this size at all in reasonable times (I tested cose, cose-bilkent and spread).

**Comment by KonradHoeffner** [comment]
A seed attribute for the randomize option would help users to always get the same layout as long as there are no changes.

**Comment by KonradHoeffner** [comment]
The anchor of the link in the issue does not seem to work.

**Comment by KonradHoeffner** [comment]
A progress callback would be great to enable progress bars for layouts on large graphs which can take more than 30 seconds.

**Comment by KonradHoeffner** [comment]
Also I need a partial layouting when I add new nodes but don't want to change the position of the old ones.

**Comment by maxkfranz** [comment]
> Also I need a partial layouting when I add new nodes but don't want to change the position of the old ones.

That's not a per-layout feature.  You can lock the old nodes.

> A progress callback would be great to enable progress bars for layouts on large graphs which can take more than 30 seconds.

The only measure for progress would be the energy/movement of the system each tick.  That's not going to give a nice value for a progress bar.  It decreases exponentially over time.  You could come up with a transformation function that gives a more linear result, but I suspect that function would change significantly given the layout options.

> Please add multi threading,

That won't help until the browsers add support for workers/threads with truly shared memory.  The layouts that currently support Weaver for threads only use one --- it just keeps the main ui thread freer and more responsive to user input.  Anything more than one thread just adds too much overhead in serialising/deserialising/synching data, with the end result being *slower* overall.

Links of interest:

- https://www.w3.org/TR/workers/
- https://html.spec.whatwg.org/multipage/workers.html
- https://hacks.mozilla.org/2016/05/a-taste-of-javascripts-new-parallel-primitives/

**Comment by maxkfranz** [comment]
> A seed attribute for the randomize option would help users to always get the same layout as long as there are no changes.

It's just using `Math.random()`, which has no seed support: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random

There's not much point in re-inventing the wheel for a RNG, so you'd have to pull in a package from npm as a dependency.  Hopefully, it would be not many kB.

**Comment by KonradHoeffner** [comment]
Thank you very much for the detailed replies! I did not know that there is no seed support for `Math.random()`, is the rest of the euler algorithm deterministic apart from the optional initial positioning or does it also use randomness?

**Comment by maxkfranz** [comment]
It's used in several places: https://github.com/cytoscape/cytoscape.js-euler/search?utf8=%E2%9C%93&q=Math.random&type=
