### ISSUE TITLE
Add weaverjs support to base layout class

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-euler#8]
weaverjs : http://weaver.js.org/

If `options.weaver` is passed to the layout, then the base layout class can use a weaver thread to run the algorithm in a separate thread.  This would only apply to the continuous / while-running-animated case.

Tasks

- [ ] Create a new `this.weaverState` object from `this.state` with only json-serialisable objects and the minimum of information needed to run the layout algorithm
- [ ] Add a new case to `Layout.run()` that uses a weaver thread
- [ ] `thread.require()` all the necessary functions
  - [ ] `tick.js`
  - [ ] `position.js`
  - [ ] `layout.preTick()`, `layout.postTick()`, `layout.tickNode()` : These functions must then be pure functions to be pulled into the thread

**Comment by KonradHoeffner** [comment]
Could you also split it into separate threads to speed up processing? I could imagine force-directed layouts to profit strongly from parallelization.

**Comment by maxkfranz** [comment]
It wouldn't speed it up unless browsers add proper shared memory support.
